# Generated by Django 4.2.3 on 2023-10-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='follow_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
