# Generated by Django 4.2.3 on 2023-10-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follow_follow_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follow_count',
        ),
        migrations.AddField(
            model_name='user',
            name='follow_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
